/*
 * Whio Resolver API
 *
 * Contract between the Whio core and resolver services.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CapabilitiesResponse {
    #[serde(rename = "contract_version")]
    pub contract_version: models::ContractVersion,
    #[serde(rename = "providers")]
    pub providers: Vec<models::ProviderCapabilities>,
}

impl CapabilitiesResponse {
    pub fn new(
        contract_version: models::ContractVersion,
        providers: Vec<models::ProviderCapabilities>,
    ) -> CapabilitiesResponse {
        CapabilitiesResponse {
            contract_version,
            providers,
        }
    }
}
