/*
 * Whio Resolver API
 *
 * Contract between the Whio core and resolver services.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogueSearchRequest {
    #[serde(rename = "query")]
    pub query: String,
    #[serde(rename = "limit")]
    pub limit: i32,
}

impl CatalogueSearchRequest {
    pub fn new(query: String, limit: i32) -> CatalogueSearchRequest {
        CatalogueSearchRequest { query, limit }
    }
}
