/*
 * Whio Resolver API
 *
 * Contract between the Whio core and resolver services.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ErrorCode {
    #[serde(rename = "invalid_request")]
    InvalidRequest,
    #[serde(rename = "source_not_found")]
    SourceNotFound,
    #[serde(rename = "unsupported_provider")]
    UnsupportedProvider,
    #[serde(rename = "resolution_failed")]
    ResolutionFailed,
    #[serde(rename = "provider_unavailable")]
    ProviderUnavailable,
    #[serde(rename = "internal_error")]
    InternalError,
}

impl std::fmt::Display for ErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::InvalidRequest => write!(f, "invalid_request"),
            Self::SourceNotFound => write!(f, "source_not_found"),
            Self::UnsupportedProvider => write!(f, "unsupported_provider"),
            Self::ResolutionFailed => write!(f, "resolution_failed"),
            Self::ProviderUnavailable => write!(f, "provider_unavailable"),
            Self::InternalError => write!(f, "internal_error"),
        }
    }
}

impl Default for ErrorCode {
    fn default() -> ErrorCode {
        Self::InvalidRequest
    }
}
