/*
 * Whio Resolver API
 *
 * Contract between the Whio core and resolver services.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaMetadata {
    #[serde(
        rename = "content_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub content_type: Option<Option<String>>,
    #[serde(
        rename = "content_length_bytes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub content_length_bytes: Option<Option<i32>>,
    #[serde(
        rename = "codec",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub codec: Option<Option<String>>,
    #[serde(
        rename = "bitrate_kbps",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub bitrate_kbps: Option<Option<f64>>,
    #[serde(
        rename = "duration_ms",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub duration_ms: Option<Option<i32>>,
}

impl MediaMetadata {
    pub fn new() -> MediaMetadata {
        MediaMetadata {
            content_type: None,
            content_length_bytes: None,
            codec: None,
            bitrate_kbps: None,
            duration_ms: None,
        }
    }
}
