/*
 * Whio Resolver API
 *
 * Contract between the Whio core and resolver services.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaybackResolveRequest {
    #[serde(rename = "source")]
    pub source: Box<models::SourceIdentity>,
}

impl PlaybackResolveRequest {
    pub fn new(source: models::SourceIdentity) -> PlaybackResolveRequest {
        PlaybackResolveRequest {
            source: Box::new(source),
        }
    }
}
