/*
 * Whio Resolver API
 *
 * Contract between the Whio core and resolver services.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaybackResolveResponse {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "headers")]
    pub headers: std::collections::HashMap<String, String>,
    #[serde(
        rename = "expires_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "media")]
    pub media: Box<models::MediaMetadata>,
}

impl PlaybackResolveResponse {
    pub fn new(
        url: String,
        headers: std::collections::HashMap<String, String>,
        media: models::MediaMetadata,
    ) -> PlaybackResolveResponse {
        PlaybackResolveResponse {
            url,
            headers,
            expires_at: None,
            media: Box::new(media),
        }
    }
}
