/*
 * Whio Resolver API
 *
 * Contract between the Whio core and resolver services.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderCapabilities {
    #[serde(rename = "provider_id")]
    pub provider_id: String,
    #[serde(rename = "capabilities")]
    pub capabilities: Vec<String>,
}

impl ProviderCapabilities {
    pub fn new(provider_id: String, capabilities: Vec<String>) -> ProviderCapabilities {
        ProviderCapabilities {
            provider_id,
            capabilities,
        }
    }
}
