/*
 * Whio Resolver API
 *
 * Contract between the Whio core and resolver services.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadyResponse {
    #[serde(rename = "status")]
    pub status: Status,
}

impl ReadyResponse {
    pub fn new(status: Status) -> ReadyResponse {
        ReadyResponse { status }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ready")]
    Ready,
}

impl Default for Status {
    fn default() -> Status {
        Self::Ready
    }
}
