/*
 * Whio Resolver API
 *
 * Contract between the Whio core and resolver services.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SourceIdentity {
    #[serde(rename = "provider_id")]
    pub provider_id: String,
    #[serde(rename = "external_id")]
    pub external_id: String,
}

impl SourceIdentity {
    pub fn new(provider_id: String, external_id: String) -> SourceIdentity {
        SourceIdentity {
            provider_id,
            external_id,
        }
    }
}
