/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Agent : Reusable metadata for a vocal agent within a structuredLyrics entry
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Agent {
    /// Opaque identifier for this agent. The value is only meaningful within the parent structuredLyrics entry and must be unique within that entry
    #[serde(rename = "id")]
    pub id: String,
    /// Semantic vocal-layer classification for cueLines that reference this agent. One of: main (lead/default vocal layer), voice (additional explicit individual voice part), bg (background vocals), group (group/chorus vocals). When a structuredLyrics entry uses agents for cue-attributed lyrics, it must define exactly one main agent
    #[serde(rename = "role")]
    pub role: Role,
    /// Optional human-readable label for this agent, such as a singer or character name from the source metadata
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl Agent {
    /// Reusable metadata for a vocal agent within a structuredLyrics entry
    pub fn new(id: String, role: Role) -> Agent {
        Agent {
            id,
            role,
            name: None,
        }
    }
}
/// Semantic vocal-layer classification for cueLines that reference this agent. One of: main (lead/default vocal layer), voice (additional explicit individual voice part), bg (background vocals), group (group/chorus vocals). When a structuredLyrics entry uses agents for cue-attributed lyrics, it must define exactly one main agent
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "main")]
    Main,
    #[serde(rename = "voice")]
    Voice,
    #[serde(rename = "bg")]
    Bg,
    #[serde(rename = "group")]
    Group,
}

impl Default for Role {
    fn default() -> Role {
        Self::Main
    }
}
