/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlbumList2 {
    /// Artist albums
    #[serde(rename = "album", skip_serializing_if = "Option::is_none")]
    pub album: Option<Vec<models::AlbumId3>>,
}

impl AlbumList2 {
    pub fn new() -> AlbumList2 {
        AlbumList2 { album: None }
    }
}
