/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AlbumId3 : Album with songs.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlbumId3 {
    /// The id of the album
    #[serde(rename = "id")]
    pub id: String,
    /// The album name.
    #[serde(rename = "name")]
    pub name: String,
    /// The album version name (Remastered, Anniversary Box Set, …).
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Artist name.
    #[serde(rename = "artist", skip_serializing_if = "Option::is_none")]
    pub artist: Option<String>,
    /// The id of the artist
    #[serde(rename = "artistId", skip_serializing_if = "Option::is_none")]
    pub artist_id: Option<String>,
    /// A covertArt id.
    #[serde(rename = "coverArt", skip_serializing_if = "Option::is_none")]
    pub cover_art: Option<String>,
    /// Number of songs
    #[serde(rename = "songCount")]
    pub song_count: i32,
    /// Total duration of the album in seconds
    #[serde(rename = "duration")]
    pub duration: i32,
    /// Number of play of the album
    #[serde(rename = "playCount", skip_serializing_if = "Option::is_none")]
    pub play_count: Option<i32>,
    /// Date the album was added. [ISO 8601]
    #[serde(rename = "created")]
    pub created: chrono::DateTime<chrono::FixedOffset>,
    /// Date the album was added. [ISO 8601]
    #[serde(rename = "starred", skip_serializing_if = "Option::is_none")]
    pub starred: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The album year
    #[serde(rename = "year", skip_serializing_if = "Option::is_none")]
    pub year: Option<i32>,
    /// The album genre
    #[serde(rename = "genre", skip_serializing_if = "Option::is_none")]
    pub genre: Option<String>,
    /// Date the album was last played. [ISO 8601]
    #[serde(rename = "played", skip_serializing_if = "Option::is_none")]
    pub played: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The user rating of the album. [1-5]
    #[serde(rename = "userRating", skip_serializing_if = "Option::is_none")]
    pub user_rating: Option<i32>,
    /// The labels producing the album.
    #[serde(rename = "recordLabels", skip_serializing_if = "Option::is_none")]
    pub record_labels: Option<Vec<models::RecordLabel>>,
    /// The album MusicBrainzID.
    #[serde(rename = "musicBrainzId", skip_serializing_if = "Option::is_none")]
    pub music_brainz_id: Option<String>,
    /// The list of all genres of the album.
    #[serde(rename = "genres", skip_serializing_if = "Option::is_none")]
    pub genres: Option<Vec<models::ItemGenre>>,
    /// The list of all album artists of the album.
    #[serde(rename = "artists", skip_serializing_if = "Option::is_none")]
    pub artists: Option<Vec<models::ArtistId3>>,
    /// The single value display artist.
    #[serde(rename = "displayArtist", skip_serializing_if = "Option::is_none")]
    pub display_artist: Option<String>,
    /// The types of this album release. (Album, Compilation, EP, Remix, …).
    #[serde(rename = "releaseTypes", skip_serializing_if = "Option::is_none")]
    pub release_types: Option<Vec<String>>,
    /// The list of all moods of the album.
    #[serde(rename = "moods", skip_serializing_if = "Option::is_none")]
    pub moods: Option<Vec<String>>,
    /// The album sort name.
    #[serde(rename = "sortName", skip_serializing_if = "Option::is_none")]
    pub sort_name: Option<String>,
    /// Date the album was originally released.
    #[serde(
        rename = "originalReleaseDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub original_release_date: Option<Box<models::ItemDate>>,
    /// Date the specific edition of the album was released. Note: for files using ID3 tags, releaseDate should generally be read from the TDRL tag. Servers that use a different source for this field should document the behavior.
    #[serde(rename = "releaseDate", skip_serializing_if = "Option::is_none")]
    pub release_date: Option<Box<models::ItemDate>>,
    /// True if the album is a compilation.
    #[serde(rename = "isCompilation", skip_serializing_if = "Option::is_none")]
    pub is_compilation: Option<bool>,
    #[serde(rename = "explicitStatus", skip_serializing_if = "Option::is_none")]
    pub explicit_status: Option<models::ExplicitStatus>,
    /// The list of all disc titles of the album.
    #[serde(rename = "discTitles", skip_serializing_if = "Option::is_none")]
    pub disc_titles: Option<Vec<models::DiscTitle>>,
    /// The list of songs
    #[serde(rename = "song", skip_serializing_if = "Option::is_none")]
    pub song: Option<Vec<models::Child>>,
}

impl AlbumId3 {
    /// Album with songs.
    pub fn new(
        id: String,
        name: String,
        song_count: i32,
        duration: i32,
        created: chrono::DateTime<chrono::FixedOffset>,
    ) -> AlbumId3 {
        AlbumId3 {
            id,
            name,
            version: None,
            artist: None,
            artist_id: None,
            cover_art: None,
            song_count,
            duration,
            play_count: None,
            created,
            starred: None,
            year: None,
            genre: None,
            played: None,
            user_rating: None,
            record_labels: None,
            music_brainz_id: None,
            genres: None,
            artists: None,
            display_artist: None,
            release_types: None,
            moods: None,
            sort_name: None,
            original_release_date: None,
            release_date: None,
            is_compilation: None,
            explicit_status: None,
            disc_titles: None,
            song: None,
        }
    }
}
