/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AlbumList : Album list.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlbumList {
    /// Artist albums
    #[serde(rename = "album", skip_serializing_if = "Option::is_none")]
    pub album: Option<Vec<models::Child>>,
}

impl AlbumList {
    /// Album list.
    pub fn new() -> AlbumList {
        AlbumList { album: None }
    }
}
