/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AlbumInfo : Album info.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlbumInfo {
    /// Album notes
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// Album musicBrainzId
    #[serde(rename = "musicBrainzId", skip_serializing_if = "Option::is_none")]
    pub music_brainz_id: Option<String>,
    /// Album lastFmUrl
    #[serde(rename = "lastFmUrl", skip_serializing_if = "Option::is_none")]
    pub last_fm_url: Option<String>,
    /// Album smallImageUrl
    #[serde(rename = "smallImageUrl", skip_serializing_if = "Option::is_none")]
    pub small_image_url: Option<String>,
    /// Album mediumImageUrl
    #[serde(rename = "mediumImageUrl", skip_serializing_if = "Option::is_none")]
    pub medium_image_url: Option<String>,
    /// Album largeImageUrl
    #[serde(rename = "largeImageUrl", skip_serializing_if = "Option::is_none")]
    pub large_image_url: Option<String>,
}

impl AlbumInfo {
    /// Album info.
    pub fn new() -> AlbumInfo {
        AlbumInfo {
            notes: None,
            music_brainz_id: None,
            last_fm_url: None,
            small_image_url: None,
            medium_image_url: None,
            large_image_url: None,
        }
    }
}
