/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AlbumListType : The list type. Must be one of the following: random, newest, highest, frequent, recent. Since 1.8.0 you can also use alphabeticalByName or alphabeticalByArtist to page through all albums alphabetically, and starred to retrieve starred albums. Since 1.10.1 you can use byYear and byGenre to list albums in a given year range or genre.
/// The list type. Must be one of the following: random, newest, highest, frequent, recent. Since 1.8.0 you can also use alphabeticalByName or alphabeticalByArtist to page through all albums alphabetically, and starred to retrieve starred albums. Since 1.10.1 you can use byYear and byGenre to list albums in a given year range or genre.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AlbumListType {
    #[serde(rename = "random")]
    Random,
    #[serde(rename = "newest")]
    Newest,
    #[serde(rename = "highest")]
    Highest,
    #[serde(rename = "frequent")]
    Frequent,
    #[serde(rename = "recent")]
    Recent,
    #[serde(rename = "alphabeticalByName")]
    AlphabeticalByName,
    #[serde(rename = "alphabeticalByArtist")]
    AlphabeticalByArtist,
    #[serde(rename = "starred")]
    Starred,
    #[serde(rename = "byYear")]
    ByYear,
    #[serde(rename = "byGenre")]
    ByGenre,
}

impl std::fmt::Display for AlbumListType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Random => write!(f, "random"),
            Self::Newest => write!(f, "newest"),
            Self::Highest => write!(f, "highest"),
            Self::Frequent => write!(f, "frequent"),
            Self::Recent => write!(f, "recent"),
            Self::AlphabeticalByName => write!(f, "alphabeticalByName"),
            Self::AlphabeticalByArtist => write!(f, "alphabeticalByArtist"),
            Self::Starred => write!(f, "starred"),
            Self::ByYear => write!(f, "byYear"),
            Self::ByGenre => write!(f, "byGenre"),
        }
    }
}

impl Default for AlbumListType {
    fn default() -> AlbumListType {
        Self::Random
    }
}
