/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Artist : Artist details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Artist {
    /// Artist id
    #[serde(rename = "id")]
    pub id: String,
    /// Artist name
    #[serde(rename = "name")]
    pub name: String,
    /// Artist image url
    #[serde(rename = "artistImageUrl", skip_serializing_if = "Option::is_none")]
    pub artist_image_url: Option<String>,
    /// Artist starred date [ISO 8601]
    #[serde(rename = "starred", skip_serializing_if = "Option::is_none")]
    pub starred: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Artist rating [1-5]
    #[serde(rename = "userRating", skip_serializing_if = "Option::is_none")]
    pub user_rating: Option<i32>,
    /// Artist average rating [1.0-5.0]
    #[serde(rename = "averageRating", skip_serializing_if = "Option::is_none")]
    pub average_rating: Option<f64>,
}

impl Artist {
    /// Artist details.
    pub fn new(id: String, name: String) -> Artist {
        Artist {
            id,
            name,
            artist_image_url: None,
            starred: None,
            user_rating: None,
            average_rating: None,
        }
    }
}
