/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ArtistInfo : Artist info.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtistInfo {
    /// Artist biography
    #[serde(rename = "biography", skip_serializing_if = "Option::is_none")]
    pub biography: Option<String>,
    /// Artist musicBrainzId
    #[serde(rename = "musicBrainzId", skip_serializing_if = "Option::is_none")]
    pub music_brainz_id: Option<String>,
    /// Artist lastFmUrl
    #[serde(rename = "lastFmUrl", skip_serializing_if = "Option::is_none")]
    pub last_fm_url: Option<String>,
    /// Artist smallImageUrl
    #[serde(rename = "smallImageUrl", skip_serializing_if = "Option::is_none")]
    pub small_image_url: Option<String>,
    /// Artist mediumImageUrl
    #[serde(rename = "mediumImageUrl", skip_serializing_if = "Option::is_none")]
    pub medium_image_url: Option<String>,
    /// Artist largeImageUrl
    #[serde(rename = "largeImageUrl", skip_serializing_if = "Option::is_none")]
    pub large_image_url: Option<String>,
    /// Similar artists
    #[serde(rename = "similarArtist", skip_serializing_if = "Option::is_none")]
    pub similar_artist: Option<Vec<models::Artist>>,
}

impl ArtistInfo {
    /// Artist info.
    pub fn new() -> ArtistInfo {
        ArtistInfo {
            biography: None,
            music_brainz_id: None,
            last_fm_url: None,
            small_image_url: None,
            medium_image_url: None,
            large_image_url: None,
            similar_artist: None,
        }
    }
}
