/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ArtistsId3 : A list of indexed Artists.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtistsId3 {
    /// List of ignored articles space separated
    #[serde(rename = "ignoredArticles", skip_serializing_if = "Option::is_none")]
    pub ignored_articles: Option<String>,
    /// Index list
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<Vec<models::IndexId3>>,
}

impl ArtistsId3 {
    /// A list of indexed Artists.
    pub fn new() -> ArtistsId3 {
        ArtistsId3 {
            ignored_articles: None,
            index: None,
        }
    }
}
