/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtistWithAlbumsId3 {
    /// The id of the artist
    #[serde(rename = "id")]
    pub id: String,
    /// The artist name.
    #[serde(rename = "name")]
    pub name: String,
    /// A covertArt id.
    #[serde(rename = "coverArt", skip_serializing_if = "Option::is_none")]
    pub cover_art: Option<String>,
    /// An url to an external image source.
    #[serde(rename = "artistImageUrl", skip_serializing_if = "Option::is_none")]
    pub artist_image_url: Option<String>,
    /// Artist album count.
    #[serde(rename = "albumCount", skip_serializing_if = "Option::is_none")]
    pub album_count: Option<i32>,
    /// Date the artist was starred. [ISO 8601]
    #[serde(rename = "starred", skip_serializing_if = "Option::is_none")]
    pub starred: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The artist MusicBrainzID.
    #[serde(rename = "musicBrainzId", skip_serializing_if = "Option::is_none")]
    pub music_brainz_id: Option<String>,
    /// The artist sort name.
    #[serde(rename = "sortName", skip_serializing_if = "Option::is_none")]
    pub sort_name: Option<String>,
    /// A short human-readable comment, meant to be shown to users to distinguish between artists with the same name (e.g. 'French electronic duo').
    #[serde(rename = "disambiguation", skip_serializing_if = "Option::is_none")]
    pub disambiguation: Option<String>,
    /// The list of all roles this artist has in the library.
    #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
    pub roles: Option<Vec<String>>,
    /// Artist albums
    #[serde(rename = "album")]
    pub album: Vec<models::AlbumId3>,
}

impl ArtistWithAlbumsId3 {
    pub fn new(id: String, name: String, album: Vec<models::AlbumId3>) -> ArtistWithAlbumsId3 {
        ArtistWithAlbumsId3 {
            id,
            name,
            cover_art: None,
            artist_image_url: None,
            album_count: None,
            starred: None,
            music_brainz_id: None,
            sort_name: None,
            disambiguation: None,
            roles: None,
            album,
        }
    }
}
