/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Bookmark : A bookmark.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Bookmark {
    /// Bookmark position in milliseconds
    #[serde(rename = "position")]
    pub position: i32,
    /// Username
    #[serde(rename = "username")]
    pub username: String,
    /// Bookmark comment
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// Bookmark creation date [ISO 8601]
    #[serde(rename = "created")]
    pub created: chrono::DateTime<chrono::FixedOffset>,
    /// Bookmark last updated date [ISO 8601]
    #[serde(rename = "changed")]
    pub changed: chrono::DateTime<chrono::FixedOffset>,
    /// The bookmark file
    #[serde(rename = "entry")]
    pub entry: Box<models::Child>,
}

impl Bookmark {
    /// A bookmark.
    pub fn new(
        position: i32,
        username: String,
        created: chrono::DateTime<chrono::FixedOffset>,
        changed: chrono::DateTime<chrono::FixedOffset>,
        entry: models::Child,
    ) -> Bookmark {
        Bookmark {
            position,
            username,
            comment: None,
            created,
            changed,
            entry: Box::new(entry),
        }
    }
}
