/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Bookmarks : Bookmarks list.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Bookmarks {
    /// List of bookmark
    #[serde(rename = "bookmark", skip_serializing_if = "Option::is_none")]
    pub bookmark: Option<Vec<models::Bookmark>>,
}

impl Bookmarks {
    /// Bookmarks list.
    pub fn new() -> Bookmarks {
        Bookmarks { bookmark: None }
    }
}
