/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatMessages : Chat messages list.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatMessages {
    /// List of chatMessage
    #[serde(rename = "chatMessage", skip_serializing_if = "Option::is_none")]
    pub chat_message: Option<Vec<models::ChatMessage>>,
}

impl ChatMessages {
    /// Chat messages list.
    pub fn new() -> ChatMessages {
        ChatMessages { chat_message: None }
    }
}
