/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatMessage : A chatMessage.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatMessage {
    /// Username
    #[serde(rename = "username")]
    pub username: String,
    /// Time in millis since Jan 1 1970
    #[serde(rename = "time")]
    pub time: i32,
    /// The message
    #[serde(rename = "message")]
    pub message: String,
}

impl ChatMessage {
    /// A chatMessage.
    pub fn new(username: String, time: i32, message: String) -> ChatMessage {
        ChatMessage {
            username,
            time,
            message,
        }
    }
}
