/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientInfo {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "maxAudioBitrate", skip_serializing_if = "Option::is_none")]
    pub max_audio_bitrate: Option<i32>,
    #[serde(
        rename = "maxTranscodingAudioBitrate",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_transcoding_audio_bitrate: Option<i32>,
    #[serde(rename = "directPlayProfiles", skip_serializing_if = "Option::is_none")]
    pub direct_play_profiles: Option<Vec<models::DirectPlayProfile>>,
    #[serde(
        rename = "transcodingProfiles",
        skip_serializing_if = "Option::is_none"
    )]
    pub transcoding_profiles: Option<Vec<models::TranscodingProfile>>,
    #[serde(rename = "codecProfiles", skip_serializing_if = "Option::is_none")]
    pub codec_profiles: Option<Vec<models::CodecProfile>>,
}

impl ClientInfo {
    pub fn new(name: String, platform: String) -> ClientInfo {
        ClientInfo {
            name,
            platform,
            max_audio_bitrate: None,
            max_transcoding_audio_bitrate: None,
            direct_play_profiles: None,
            transcoding_profiles: None,
            codec_profiles: None,
        }
    }
}
