/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodecProfile {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "limitations", skip_serializing_if = "Option::is_none")]
    pub limitations: Option<Vec<models::Limitation>>,
}

impl CodecProfile {
    pub fn new(r#type: Type, name: String) -> CodecProfile {
        CodecProfile {
            r#type,
            name,
            limitations: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "AudioCodec")]
    AudioCodec,
}

impl Default for Type {
    fn default() -> Type {
        Self::AudioCodec
    }
}
