/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Contributor : A contributor artist for a song or an album
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Contributor {
    /// The contributor role.
    #[serde(rename = "role")]
    pub role: String,
    /// The subRole for roles that may require it. Ex: The instrument for the performer role (TMCL/performer tags). Note: For consistency between different tag formats, the TIPL sub roles should be directly exposed in the role field.
    #[serde(rename = "subRole", skip_serializing_if = "Option::is_none")]
    pub sub_role: Option<String>,
    #[serde(rename = "artist")]
    pub artist: Box<models::ArtistId3>,
}

impl Contributor {
    /// A contributor artist for a song or an album
    pub fn new(role: String, artist: models::ArtistId3) -> Contributor {
        Contributor {
            role,
            sub_role: None,
            artist: Box::new(artist),
        }
    }
}
