/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateSharesResponse : A subsonic-response element with a nested shares element on success. Which in turns contains a single share element for the newly created share
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSharesResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::CreateSharesResponseSubsonicResponse>>,
}

impl CreateSharesResponse {
    /// A subsonic-response element with a nested shares element on success. Which in turns contains a single share element for the newly created share
    pub fn new() -> CreateSharesResponse {
        CreateSharesResponse {
            subsonic_response: None,
        }
    }
}
