/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Cue : A word or syllable cue within a cueLine
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Cue {
    /// Start time in milliseconds
    #[serde(rename = "start")]
    pub start: i32,
    /// End time in milliseconds. Within a cueLine, end must be either present on all cues or none. When the source provides partial end times, servers must fill missing values (e.g., using the next cue's start, or the cueLine's end for the final cue). When no cues have end times (e.g., Enhanced LRC with start-only timing), end is omitted from all cues. This is a documented contract rule; this schema does not enforce the all-or-none shape structurally
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<i32>,
    /// Required zero-based inclusive UTF-8 byte offset into the parent cueLine.value where this cue begins. The parent cueLine must include value, and the offsets must be calculated against the final cueLine.value with no normalization step
    #[serde(rename = "byteStart")]
    pub byte_start: i32,
    /// Required zero-based inclusive UTF-8 byte offset into the parent cueLine.value where this cue ends. byteStart must be less than or equal to byteEnd, the parent cueLine must include value, and the offsets must be calculated against the final cueLine.value with no normalization step. This schema does not enforce the cross-field ordering constraint structurally
    #[serde(rename = "byteEnd")]
    pub byte_end: i32,
    /// The text of this word or syllable
    #[serde(rename = "value")]
    pub value: String,
}

impl Cue {
    /// A word or syllable cue within a cueLine
    pub fn new(start: i32, byte_start: i32, byte_end: i32, value: String) -> Cue {
        Cue {
            start,
            end: None,
            byte_start,
            byte_end,
            value,
        }
    }
}
