/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CueLine : Word/syllable-level timing data for a lyrics line or agent layer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CueLine {
    /// Zero-based index into the parent line array this cueLine corresponds to
    #[serde(rename = "index")]
    pub index: i32,
    /// Start time in milliseconds (may differ from the parent line if cues are more precise)
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i32>,
    /// End time in milliseconds
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<i32>,
    /// Required full text for this cueLine. When agent attribution splits one parent line into multiple cueLines, this is the text for that cueLine's agent/layer, not necessarily the parent line's combined text. Nested cue byteStart and byteEnd offsets are always calculated against this exact final UTF-8 string
    #[serde(rename = "value")]
    pub value: String,
    /// Opaque identifier referencing an agent in the same structuredLyrics entry. If the parent structuredLyrics entry includes agents, every cueLine in that entry must include agentId, and the value must match exactly one agents[].id in that entry. If the parent entry does not include agents, cueLines must not include agentId. When multiple cueLines share the same index, the cueLine whose referenced agent has role main must come first
    #[serde(rename = "agentId", skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<String>,
    /// Ordered list of word/syllable cues. Every cue includes required byteStart and byteEnd offsets into value
    #[serde(rename = "cue")]
    pub cue: Vec<models::Cue>,
}

impl CueLine {
    /// Word/syllable-level timing data for a lyrics line or agent layer
    pub fn new(index: i32, value: String, cue: Vec<models::Cue>) -> CueLine {
        CueLine {
            index,
            start: None,
            end: None,
            value,
            agent_id: None,
            cue,
        }
    }
}
