/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DirectPlayProfile {
    /// The list of supported containers. An empty array means any containers.
    #[serde(rename = "containers")]
    pub containers: Vec<String>,
    /// The list of supported codecs. An empty array means any codecs.
    #[serde(rename = "audioCodecs")]
    pub audio_codecs: Vec<String>,
    /// The list of supported protocols. An empty array means any protocols.
    #[serde(rename = "protocols")]
    pub protocols: Vec<Protocols>,
    #[serde(rename = "maxAudioChannels", skip_serializing_if = "Option::is_none")]
    pub max_audio_channels: Option<i32>,
}

impl DirectPlayProfile {
    pub fn new(
        containers: Vec<String>,
        audio_codecs: Vec<String>,
        protocols: Vec<Protocols>,
    ) -> DirectPlayProfile {
        DirectPlayProfile {
            containers,
            audio_codecs,
            protocols,
            max_audio_channels: None,
        }
    }
}
/// The list of supported protocols. An empty array means any protocols.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Protocols {
    #[serde(rename = "http")]
    Http,
    #[serde(rename = "hls")]
    Hls,
}

impl Default for Protocols {
    fn default() -> Protocols {
        Self::Http
    }
}
