/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Directory : Directory.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Directory {
    /// The id
    #[serde(rename = "id")]
    pub id: String,
    /// Parent item
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,
    /// The directory name
    #[serde(rename = "name")]
    pub name: String,
    /// Starred date [ISO 8601]
    #[serde(rename = "starred", skip_serializing_if = "Option::is_none")]
    pub starred: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The user rating [1-5]
    #[serde(rename = "userRating", skip_serializing_if = "Option::is_none")]
    pub user_rating: Option<i32>,
    /// The average rating [1-5]
    #[serde(rename = "averageRating", skip_serializing_if = "Option::is_none")]
    pub average_rating: Option<f64>,
    /// The play count
    #[serde(rename = "playCount", skip_serializing_if = "Option::is_none")]
    pub play_count: Option<i32>,
    /// The directory content
    #[serde(rename = "child", skip_serializing_if = "Option::is_none")]
    pub child: Option<Vec<models::Child>>,
}

impl Directory {
    /// Directory.
    pub fn new(id: String, name: String) -> Directory {
        Directory {
            id,
            parent: None,
            name,
            starred: None,
            user_rating: None,
            average_rating: None,
            play_count: None,
            child: None,
        }
    }
}
