/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscTitle : A disc title for an album with an optional cover art
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscTitle {
    /// The disc number.
    #[serde(rename = "disc")]
    pub disc: i32,
    /// The name of the disc.
    #[serde(rename = "title")]
    pub title: String,
    /// The cover art ID of the disc.
    #[serde(rename = "coverArt", skip_serializing_if = "Option::is_none")]
    pub cover_art: Option<String>,
}

impl DiscTitle {
    /// A disc title for an album with an optional cover art
    pub fn new(disc: i32, title: String) -> DiscTitle {
        DiscTitle {
            disc,
            title,
            cover_art: None,
        }
    }
}
