/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExplicitStatus : Returns “explicit”, “clean” or “”. (For songs extracted from tags “ITUNESADVISORY”: 1 = explicit, 2 = clean, MP4 “rtng”: 1 or 4 = explicit, 2 = clean. See `albumID3` for albums)
/// Returns “explicit”, “clean” or “”. (For songs extracted from tags “ITUNESADVISORY”: 1 = explicit, 2 = clean, MP4 “rtng”: 1 or 4 = explicit, 2 = clean. See `albumID3` for albums)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExplicitStatus {
    #[serde(rename = "clean")]
    Clean,
    #[serde(rename = "explicit")]
    Explicit,
    #[serde(rename = "")]
    Empty,
}

impl std::fmt::Display for ExplicitStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Clean => write!(f, "clean"),
            Self::Explicit => write!(f, "explicit"),
            Self::Empty => write!(f, ""),
        }
    }
}

impl Default for ExplicitStatus {
    fn default() -> ExplicitStatus {
        Self::Clean
    }
}
