/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GenericMediaType : The generic type of media [music/podcast/audiobook/video]
/// The generic type of media [music/podcast/audiobook/video]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GenericMediaType {
    #[serde(rename = "music")]
    Music,
    #[serde(rename = "video")]
    Video,
    #[serde(rename = "podcast")]
    Podcast,
    #[serde(rename = "audiobook")]
    Audiobook,
}

impl std::fmt::Display for GenericMediaType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Music => write!(f, "music"),
            Self::Video => write!(f, "video"),
            Self::Podcast => write!(f, "podcast"),
            Self::Audiobook => write!(f, "audiobook"),
        }
    }
}

impl Default for GenericMediaType {
    fn default() -> GenericMediaType {
        Self::Music
    }
}
