/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Genre : A genre.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Genre {
    /// Genre name
    #[serde(rename = "value")]
    pub value: String,
    /// Genre song count
    #[serde(rename = "songCount")]
    pub song_count: i32,
    /// Genre album count
    #[serde(rename = "albumCount")]
    pub album_count: i32,
}

impl Genre {
    /// A genre.
    pub fn new(value: String, song_count: i32, album_count: i32) -> Genre {
        Genre {
            value,
            song_count,
            album_count,
        }
    }
}
