/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Genres : Genres list.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Genres {
    /// List of genre
    #[serde(rename = "genre", skip_serializing_if = "Option::is_none")]
    pub genre: Option<Vec<models::Genre>>,
}

impl Genres {
    /// Genres list.
    pub fn new() -> Genres {
        Genres { genre: None }
    }
}
