/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetRandomSongsResponse : A subsonic-response element with a nested `randomSongs` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRandomSongsResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetRandomSongsResponseSubsonicResponse>>,
}

impl GetRandomSongsResponse {
    /// A subsonic-response element with a nested `randomSongs` element on success.
    pub fn new() -> GetRandomSongsResponse {
        GetRandomSongsResponse {
            subsonic_response: None,
        }
    }
}
