/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetPodcastEpisodeResponse : A subsonic-response element with a nested `podcastEpisode` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPodcastEpisodeResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetPodcastEpisodeResponseSubsonicResponse>>,
}

impl GetPodcastEpisodeResponse {
    /// A subsonic-response element with a nested `podcastEpisode` element on success.
    pub fn new() -> GetPodcastEpisodeResponse {
        GetPodcastEpisodeResponse {
            subsonic_response: None,
        }
    }
}
