/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSongsByGenreResponse : A subsonic-response element with a nested `songsByGenre` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSongsByGenreResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetSongsByGenreResponseSubsonicResponse>>,
}

impl GetSongsByGenreResponse {
    /// A subsonic-response element with a nested `songsByGenre` element on success.
    pub fn new() -> GetSongsByGenreResponse {
        GetSongsByGenreResponse {
            subsonic_response: None,
        }
    }
}
