/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetBookmarksResponse : A subsonic-response element with a nested bookmarks element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBookmarksResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetBookmarksResponseSubsonicResponse>>,
}

impl GetBookmarksResponse {
    /// A subsonic-response element with a nested bookmarks element on success.
    pub fn new() -> GetBookmarksResponse {
        GetBookmarksResponse {
            subsonic_response: None,
        }
    }
}
