/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetArtistsResponse : A subsonic-response element with a nested artists element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetArtistsResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetArtistsResponseSubsonicResponse>>,
}

impl GetArtistsResponse {
    /// A subsonic-response element with a nested artists element on success.
    pub fn new() -> GetArtistsResponse {
        GetArtistsResponse {
            subsonic_response: None,
        }
    }
}
