/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetArtistInfoResponse : A subsonic-response element with a nested artistInfo element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetArtistInfoResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetArtistInfoResponseSubsonicResponse>>,
}

impl GetArtistInfoResponse {
    /// A subsonic-response element with a nested artistInfo element on success.
    pub fn new() -> GetArtistInfoResponse {
        GetArtistInfoResponse {
            subsonic_response: None,
        }
    }
}
