/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetUsersResponse : A subsonic-response element with a nested `user` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUsersResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetUsersResponseSubsonicResponse>>,
}

impl GetUsersResponse {
    /// A subsonic-response element with a nested `user` element on success.
    pub fn new() -> GetUsersResponse {
        GetUsersResponse {
            subsonic_response: None,
        }
    }
}
