/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetLicenseResponse : A subsonic-response element with a nested license element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLicenseResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetLicenseResponseSubsonicResponse>>,
}

impl GetLicenseResponse {
    /// A subsonic-response element with a nested license element on success.
    pub fn new() -> GetLicenseResponse {
        GetLicenseResponse {
            subsonic_response: None,
        }
    }
}
