/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetArtistInfo2Response : A subsonic-response element with a nested artistInfo2 element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetArtistInfo2Response {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetArtistInfo2ResponseSubsonicResponse>>,
}

impl GetArtistInfo2Response {
    /// A subsonic-response element with a nested artistInfo2 element on success.
    pub fn new() -> GetArtistInfo2Response {
        GetArtistInfo2Response {
            subsonic_response: None,
        }
    }
}
