/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetChatMessagesResponse : A subsonic-response element with a nested chatMessages element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetChatMessagesResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetChatMessagesResponseSubsonicResponse>>,
}

impl GetChatMessagesResponse {
    /// A subsonic-response element with a nested chatMessages element on success.
    pub fn new() -> GetChatMessagesResponse {
        GetChatMessagesResponse {
            subsonic_response: None,
        }
    }
}
