/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetTokenInfoResponse : A subsonic-response element with a nested tokenInfo on success, or error 44 on invalid token.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTokenInfoResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetTokenInfoResponseSubsonicResponse>>,
}

impl GetTokenInfoResponse {
    /// A subsonic-response element with a nested tokenInfo on success, or error 44 on invalid token.
    pub fn new() -> GetTokenInfoResponse {
        GetTokenInfoResponse {
            subsonic_response: None,
        }
    }
}
