/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetAlbumInfoResponse : A subsonic-response element with a nested albumInfo element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAlbumInfoResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetAlbumInfoResponseSubsonicResponse>>,
}

impl GetAlbumInfoResponse {
    /// A subsonic-response element with a nested albumInfo element on success.
    pub fn new() -> GetAlbumInfoResponse {
        GetAlbumInfoResponse {
            subsonic_response: None,
        }
    }
}
