/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetMusicDirectoryResponse : A subsonic-response element with a nested directory element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMusicDirectoryResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetMusicDirectoryResponseSubsonicResponse>>,
}

impl GetMusicDirectoryResponse {
    /// A subsonic-response element with a nested directory element on success.
    pub fn new() -> GetMusicDirectoryResponse {
        GetMusicDirectoryResponse {
            subsonic_response: None,
        }
    }
}
