/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetAlbumResponse : A subsonic-response element with a nested album element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAlbumResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetAlbumResponseSubsonicResponse>>,
}

impl GetAlbumResponse {
    /// A subsonic-response element with a nested album element on success.
    pub fn new() -> GetAlbumResponse {
        GetAlbumResponse {
            subsonic_response: None,
        }
    }
}
