/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSongResponse : A subsonic-response element with a nested `song` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSongResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetSongResponseSubsonicResponse>>,
}

impl GetSongResponse {
    /// A subsonic-response element with a nested `song` element on success.
    pub fn new() -> GetSongResponse {
        GetSongResponse {
            subsonic_response: None,
        }
    }
}
