/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetNewestPodcastsResponse : A subsonic-response element with a nested `newestPodcasts` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNewestPodcastsResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetNewestPodcastsResponseSubsonicResponse>>,
}

impl GetNewestPodcastsResponse {
    /// A subsonic-response element with a nested `newestPodcasts` element on success.
    pub fn new() -> GetNewestPodcastsResponse {
        GetNewestPodcastsResponse {
            subsonic_response: None,
        }
    }
}
