/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetInternetRadioStationsResponse : A subsonic-response element with a nested internetRadioStations element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetInternetRadioStationsResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetInternetRadioStationsResponseSubsonicResponse>>,
}

impl GetInternetRadioStationsResponse {
    /// A subsonic-response element with a nested internetRadioStations element on success.
    pub fn new() -> GetInternetRadioStationsResponse {
        GetInternetRadioStationsResponse {
            subsonic_response: None,
        }
    }
}
