/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetPlaylistsResponse : A subsonic-response element with a nested `playlists` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPlaylistsResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetPlaylistsResponseSubsonicResponse>>,
}

impl GetPlaylistsResponse {
    /// A subsonic-response element with a nested `playlists` element on success.
    pub fn new() -> GetPlaylistsResponse {
        GetPlaylistsResponse {
            subsonic_response: None,
        }
    }
}
