/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetNowPlayingResponse : A subsonic-response element with a nested `nowPlaying` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNowPlayingResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetNowPlayingResponseSubsonicResponse>>,
}

impl GetNowPlayingResponse {
    /// A subsonic-response element with a nested `nowPlaying` element on success.
    pub fn new() -> GetNowPlayingResponse {
        GetNowPlayingResponse {
            subsonic_response: None,
        }
    }
}
