/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSharesResponse : A subsonic-response element with a nested `shares` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSharesResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetSharesResponseSubsonicResponse>>,
}

impl GetSharesResponse {
    /// A subsonic-response element with a nested `shares` element on success.
    pub fn new() -> GetSharesResponse {
        GetSharesResponse {
            subsonic_response: None,
        }
    }
}
