/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSimilarSongsResponse : A subsonic-response element with a nested `similarSongs` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSimilarSongsResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetSimilarSongsResponseSubsonicResponse>>,
}

impl GetSimilarSongsResponse {
    /// A subsonic-response element with a nested `similarSongs` element on success.
    pub fn new() -> GetSimilarSongsResponse {
        GetSimilarSongsResponse {
            subsonic_response: None,
        }
    }
}
