/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetGenresResponse : A subsonic-response element with a nested genres element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGenresResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetGenresResponseSubsonicResponse>>,
}

impl GetGenresResponse {
    /// A subsonic-response element with a nested genres element on success.
    pub fn new() -> GetGenresResponse {
        GetGenresResponse {
            subsonic_response: None,
        }
    }
}
