/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetPlaylistResponse : A subsonic-response element with a nested playlist element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPlaylistResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetPlaylistResponseSubsonicResponse>>,
}

impl GetPlaylistResponse {
    /// A subsonic-response element with a nested playlist element on success.
    pub fn new() -> GetPlaylistResponse {
        GetPlaylistResponse {
            subsonic_response: None,
        }
    }
}
