/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTranscodeDecision200Response {
    #[serde(rename = "transcodeDecision", skip_serializing_if = "Option::is_none")]
    pub transcode_decision: Option<Box<models::TranscodeDecision>>,
}

impl GetTranscodeDecision200Response {
    pub fn new() -> GetTranscodeDecision200Response {
        GetTranscodeDecision200Response {
            transcode_decision: None,
        }
    }
}
