/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSonicSimilarTracksResponse : A subsonic-response element with a direct `sonicMatch` array on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSonicSimilarTracksResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetSonicSimilarTracksResponseSubsonicResponse>>,
}

impl GetSonicSimilarTracksResponse {
    /// A subsonic-response element with a direct `sonicMatch` array on success.
    pub fn new() -> GetSonicSimilarTracksResponse {
        GetSonicSimilarTracksResponse {
            subsonic_response: None,
        }
    }
}
