/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetLyricsResponse : A subsonic-response element with a nested lyrics element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLyricsResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetLyricsResponseSubsonicResponse>>,
}

impl GetLyricsResponse {
    /// A subsonic-response element with a nested lyrics element on success.
    pub fn new() -> GetLyricsResponse {
        GetLyricsResponse {
            subsonic_response: None,
        }
    }
}
