/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetPlayQueueResponse : A subsonic-response element with a nested `playQueue` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPlayQueueResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetPlayQueueResponseSubsonicResponse>>,
}

impl GetPlayQueueResponse {
    /// A subsonic-response element with a nested `playQueue` element on success.
    pub fn new() -> GetPlayQueueResponse {
        GetPlayQueueResponse {
            subsonic_response: None,
        }
    }
}
