/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetArtistResponse : A subsonic-response element with a nested artist element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetArtistResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetArtistResponseSubsonicResponse>>,
}

impl GetArtistResponse {
    /// A subsonic-response element with a nested artist element on success.
    pub fn new() -> GetArtistResponse {
        GetArtistResponse {
            subsonic_response: None,
        }
    }
}
