/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetVideoInfoResponse : A subsonic-response element with a nested `videoInfo` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVideoInfoResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetVideoInfoResponseSubsonicResponse>>,
}

impl GetVideoInfoResponse {
    /// A subsonic-response element with a nested `videoInfo` element on success.
    pub fn new() -> GetVideoInfoResponse {
        GetVideoInfoResponse {
            subsonic_response: None,
        }
    }
}
