/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetOpenSubsonicExtensionsResponse : A subsonic-response element with a nested `openSubsonicExtensions` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOpenSubsonicExtensionsResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetOpenSubsonicExtensionsResponseSubsonicResponse>>,
}

impl GetOpenSubsonicExtensionsResponse {
    /// A subsonic-response element with a nested `openSubsonicExtensions` element on success.
    pub fn new() -> GetOpenSubsonicExtensionsResponse {
        GetOpenSubsonicExtensionsResponse {
            subsonic_response: None,
        }
    }
}
