/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetLyricsBySongIdResponse : A subsonic-response element with a nested lyricsList
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLyricsBySongIdResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetLyricsBySongIdResponseSubsonicResponse>>,
}

impl GetLyricsBySongIdResponse {
    /// A subsonic-response element with a nested lyricsList
    pub fn new() -> GetLyricsBySongIdResponse {
        GetLyricsBySongIdResponse {
            subsonic_response: None,
        }
    }
}
