/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetIndexesResponse : A subsonic-response element with a nested indexes element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetIndexesResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetIndexesResponseSubsonicResponse>>,
}

impl GetIndexesResponse {
    /// A subsonic-response element with a nested indexes element on success.
    pub fn new() -> GetIndexesResponse {
        GetIndexesResponse {
            subsonic_response: None,
        }
    }
}
