/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetTopSongsResponse : A subsonic-response element with a nested `topSongs` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTopSongsResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::GetTopSongsResponseSubsonicResponse>>,
}

impl GetTopSongsResponse {
    /// A subsonic-response element with a nested `topSongs` element on success.
    pub fn new() -> GetTopSongsResponse {
        GetTopSongsResponse {
            subsonic_response: None,
        }
    }
}
