/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Index : An indexed artist list.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Index {
    /// Index name
    #[serde(rename = "name")]
    pub name: String,
    /// Artist list
    #[serde(rename = "artist", skip_serializing_if = "Option::is_none")]
    pub artist: Option<Vec<models::Artist>>,
}

impl Index {
    /// An indexed artist list.
    pub fn new(name: String) -> Index {
        Index { name, artist: None }
    }
}
