/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Indexes : Artist list.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Indexes {
    /// The ignored articles
    #[serde(rename = "ignoredArticles")]
    pub ignored_articles: String,
    /// Last time the index was modified in milliseconds after January 1, 1970 UTC
    #[serde(rename = "lastModified")]
    pub last_modified: i32,
    /// Shortcut
    #[serde(rename = "shortcut", skip_serializing_if = "Option::is_none")]
    pub shortcut: Option<Vec<models::Artist>>,
    /// Array of children
    #[serde(rename = "child", skip_serializing_if = "Option::is_none")]
    pub child: Option<Vec<models::Child>>,
    /// Indexed artists
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<Vec<models::Index>>,
}

impl Indexes {
    /// Artist list.
    pub fn new(ignored_articles: String, last_modified: i32) -> Indexes {
        Indexes {
            ignored_articles,
            last_modified,
            shortcut: None,
            child: None,
            index: None,
        }
    }
}
