/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IndexId3 : An indexed artist list by ID3 tags.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexId3 {
    /// Index name
    #[serde(rename = "name")]
    pub name: String,
    /// Artist list
    #[serde(rename = "artist", skip_serializing_if = "Option::is_none")]
    pub artist: Option<Vec<models::ArtistId3>>,
}

impl IndexId3 {
    /// An indexed artist list by ID3 tags.
    pub fn new(name: String) -> IndexId3 {
        IndexId3 { name, artist: None }
    }
}
