/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InternetRadioStations : internetRadioStations.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InternetRadioStations {
    /// A list of internetRadioStation
    #[serde(
        rename = "internetRadioStation",
        skip_serializing_if = "Option::is_none"
    )]
    pub internet_radio_station: Option<Vec<models::InternetRadioStation>>,
}

impl InternetRadioStations {
    /// internetRadioStations.
    pub fn new() -> InternetRadioStations {
        InternetRadioStations {
            internet_radio_station: None,
        }
    }
}
