/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InternetRadioStation : An internetRadioStation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InternetRadioStation {
    /// The Id
    #[serde(rename = "id")]
    pub id: String,
    /// The name
    #[serde(rename = "name")]
    pub name: String,
    /// The streamUrl
    #[serde(rename = "streamUrl")]
    pub stream_url: String,
    /// The home page URL for the station.
    #[serde(rename = "homePageUrl", skip_serializing_if = "Option::is_none")]
    pub home_page_url: Option<String>,
    /// The cover art id.
    #[serde(rename = "coverArt", skip_serializing_if = "Option::is_none")]
    pub cover_art: Option<String>,
}

impl InternetRadioStation {
    /// An internetRadioStation.
    pub fn new(id: String, name: String, stream_url: String) -> InternetRadioStation {
        InternetRadioStation {
            id,
            name,
            stream_url,
            home_page_url: None,
            cover_art: None,
        }
    }
}
