/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ItemDate : A date for a media item that may be just a year, or year-month, or full date.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemDate {
    /// The year
    #[serde(rename = "year", skip_serializing_if = "Option::is_none")]
    pub year: Option<i32>,
    /// The month (1-12)
    #[serde(rename = "month", skip_serializing_if = "Option::is_none")]
    pub month: Option<i32>,
    /// The day (1-31)
    #[serde(rename = "day", skip_serializing_if = "Option::is_none")]
    pub day: Option<i32>,
}

impl ItemDate {
    /// A date for a media item that may be just a year, or year-month, or full date.
    pub fn new() -> ItemDate {
        ItemDate {
            year: None,
            month: None,
            day: None,
        }
    }
}
