/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ItemGenre : A genre returned in list of genres for an item.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemGenre {
    /// Genre name
    #[serde(rename = "name")]
    pub name: String,
}

impl ItemGenre {
    /// A genre returned in list of genres for an item.
    pub fn new(name: String) -> ItemGenre {
        ItemGenre { name }
    }
}
