/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JukeboxPlaylist {
    /// The current index of the song being played
    #[serde(rename = "currentIndex")]
    pub current_index: i32,
    /// Whether the queue is currently playing
    #[serde(rename = "playing")]
    pub playing: bool,
    /// Volume, in a range of [0.0, 1.0]
    #[serde(rename = "volume")]
    pub volume: i32,
    /// The current position of the track in seconds
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
    /// The songs currently enqueued in the jukebox
    #[serde(rename = "entry", skip_serializing_if = "Option::is_none")]
    pub entry: Option<Vec<models::Child>>,
}

impl JukeboxPlaylist {
    pub fn new(current_index: i32, playing: bool, volume: i32) -> JukeboxPlaylist {
        JukeboxPlaylist {
            current_index,
            playing,
            volume,
            position: None,
            entry: None,
        }
    }
}
