/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JukeboxAction : JukeBox action.
/// JukeBox action.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JukeboxAction {
    #[serde(rename = "get")]
    Get,
    #[serde(rename = "status")]
    Status,
    #[serde(rename = "set")]
    Set,
    #[serde(rename = "start")]
    Start,
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "skip")]
    Skip,
    #[serde(rename = "add")]
    Add,
    #[serde(rename = "clear")]
    Clear,
    #[serde(rename = "remove")]
    Remove,
    #[serde(rename = "shuffle")]
    Shuffle,
    #[serde(rename = "setGain")]
    SetGain,
}

impl std::fmt::Display for JukeboxAction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Get => write!(f, "get"),
            Self::Status => write!(f, "status"),
            Self::Set => write!(f, "set"),
            Self::Start => write!(f, "start"),
            Self::Stop => write!(f, "stop"),
            Self::Skip => write!(f, "skip"),
            Self::Add => write!(f, "add"),
            Self::Clear => write!(f, "clear"),
            Self::Remove => write!(f, "remove"),
            Self::Shuffle => write!(f, "shuffle"),
            Self::SetGain => write!(f, "setGain"),
        }
    }
}

impl Default for JukeboxAction {
    fn default() -> JukeboxAction {
        Self::Get
    }
}
