/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JukeboxControlResponse : A subsonic-response element with a nested :  - jukeboxStatus for all actions but get - jukeboxPlaylist for get action
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JukeboxControlResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::JukeboxControlResponseSubsonicResponse>>,
}

impl JukeboxControlResponse {
    /// A subsonic-response element with a nested :  - jukeboxStatus for all actions but get - jukeboxPlaylist for get action
    pub fn new() -> JukeboxControlResponse {
        JukeboxControlResponse {
            subsonic_response: None,
        }
    }
}
