/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// License : getLicense result.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct License {
    /// The status of the license
    #[serde(rename = "valid")]
    pub valid: bool,
    /// User email
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// End of license date. [ISO 8601]
    #[serde(rename = "licenseExpires", skip_serializing_if = "Option::is_none")]
    pub license_expires: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// End of trial date. [ISO 8601]
    #[serde(rename = "trialExpires", skip_serializing_if = "Option::is_none")]
    pub trial_expires: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl License {
    /// getLicense result.
    pub fn new(valid: bool) -> License {
        License {
            valid,
            email: None,
            license_expires: None,
            trial_expires: None,
        }
    }
}
