/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Limitation {
    /// The name of the limitation.
    #[serde(rename = "name")]
    pub name: Name,
    /// The comparison operator.
    #[serde(rename = "comparison")]
    pub comparison: Comparison,
    /// The values to compare against. For LessThanEqual and GreaterThanEqual only the first value will be used.
    #[serde(rename = "values")]
    pub values: Vec<String>,
    /// Whether this limitation is required.
    #[serde(rename = "required")]
    pub required: bool,
}

impl Limitation {
    pub fn new(
        name: Name,
        comparison: Comparison,
        values: Vec<String>,
        required: bool,
    ) -> Limitation {
        Limitation {
            name,
            comparison,
            values,
            required,
        }
    }
}
/// The name of the limitation.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "audioChannels")]
    AudioChannels,
    #[serde(rename = "audioBitrate")]
    AudioBitrate,
    #[serde(rename = "audioProfile")]
    AudioProfile,
    #[serde(rename = "audioSamplerate")]
    AudioSamplerate,
    #[serde(rename = "audioBitdepth")]
    AudioBitdepth,
}

impl Default for Name {
    fn default() -> Name {
        Self::AudioChannels
    }
}
/// The comparison operator.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Comparison {
    #[serde(rename = "Equals")]
    Equals,
    #[serde(rename = "NotEquals")]
    NotEquals,
    #[serde(rename = "LessThanEqual")]
    LessThanEqual,
    #[serde(rename = "GreaterThanEqual")]
    GreaterThanEqual,
}

impl Default for Comparison {
    fn default() -> Comparison {
        Self::Equals
    }
}
