/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Line : One line of a song lyric
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Line {
    /// The actual text of this line
    #[serde(rename = "value")]
    pub value: String,
    /// The start time of the lyrics, relative to the start time of the track, in milliseconds. If this is not part of synced lyrics, start __must__ be omitted
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<f64>,
}

impl Line {
    /// One line of a song lyric
    pub fn new(value: String) -> Line {
        Line { value, start: None }
    }
}
