/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LyricsList : List of structured lyrics
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LyricsList {
    /// Structured lyrics. There can be multiple lyrics of the same type with the same language
    #[serde(rename = "structuredLyrics", skip_serializing_if = "Option::is_none")]
    pub structured_lyrics: Option<Vec<models::StructuredLyrics>>,
}

impl LyricsList {
    /// List of structured lyrics
    pub fn new() -> LyricsList {
        LyricsList {
            structured_lyrics: None,
        }
    }
}
