/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Lyrics : Lyrics.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Lyrics {
    /// The lyrics
    #[serde(rename = "value")]
    pub value: String,
    /// The artist name
    #[serde(rename = "artist", skip_serializing_if = "Option::is_none")]
    pub artist: Option<String>,
    /// The song title
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl Lyrics {
    /// Lyrics.
    pub fn new(value: String) -> Lyrics {
        Lyrics {
            value,
            artist: None,
            title: None,
        }
    }
}
