/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MediaType : Note: If you support `musicBrainzId` you must support this field to ensure clients knows what the ID refers to.
/// Note: If you support `musicBrainzId` you must support this field to ensure clients knows what the ID refers to.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MediaType {
    #[serde(rename = "song")]
    Song,
    #[serde(rename = "album")]
    Album,
    #[serde(rename = "artist")]
    Artist,
}

impl std::fmt::Display for MediaType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Song => write!(f, "song"),
            Self::Album => write!(f, "album"),
            Self::Artist => write!(f, "artist"),
        }
    }
}

impl Default for MediaType {
    fn default() -> MediaType {
        Self::Song
    }
}
