/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Movement : A movement associated with a song.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Movement {
    /// The movement name.
    #[serde(rename = "name")]
    pub name: String,
    /// The movement number.
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<i32>,
    /// The total number of movements.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}

impl Movement {
    /// A movement associated with a song.
    pub fn new(name: String) -> Movement {
        Movement {
            name,
            number: None,
            count: None,
        }
    }
}
