/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MusicFolders : MusicFolders.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MusicFolders {
    /// The folders
    #[serde(rename = "musicFolder", skip_serializing_if = "Option::is_none")]
    pub music_folder: Option<Vec<models::MusicFolder>>,
}

impl MusicFolders {
    /// MusicFolders.
    pub fn new() -> MusicFolders {
        MusicFolders { music_folder: None }
    }
}
