/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MusicFolder : MusicFolder.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MusicFolder {
    /// The id
    #[serde(rename = "id")]
    pub id: i32,
    /// The folder name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl MusicFolder {
    /// MusicFolder.
    pub fn new(id: i32) -> MusicFolder {
        MusicFolder { id, name: None }
    }
}
