/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NewestPodcasts : NewestPodcasts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewestPodcasts {
    #[serde(rename = "episode", skip_serializing_if = "Option::is_none")]
    pub episode: Option<Vec<models::PodcastEpisode>>,
}

impl NewestPodcasts {
    /// NewestPodcasts.
    pub fn new() -> NewestPodcasts {
        NewestPodcasts { episode: None }
    }
}
