/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NowPlaying : nowPlaying.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NowPlaying {
    /// The now playing entries
    #[serde(rename = "entry")]
    pub entry: Vec<models::NowPlayingEntry>,
}

impl NowPlaying {
    /// nowPlaying.
    pub fn new(entry: Vec<models::NowPlayingEntry>) -> NowPlaying {
        NowPlaying { entry }
    }
}
