/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NowPlayingEntry {
    /// The id of the media.
    #[serde(rename = "id")]
    pub id: String,
    /// The id of the parent (folder/album)
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,
    /// The media is a directory
    #[serde(rename = "isDir")]
    pub is_dir: bool,
    /// The media name.
    #[serde(rename = "title")]
    pub title: String,
    /// The album name.
    #[serde(rename = "album", skip_serializing_if = "Option::is_none")]
    pub album: Option<String>,
    /// The artist name.
    #[serde(rename = "artist", skip_serializing_if = "Option::is_none")]
    pub artist: Option<String>,
    /// The track number.
    #[serde(rename = "track", skip_serializing_if = "Option::is_none")]
    pub track: Option<i32>,
    /// The media year.
    #[serde(rename = "year", skip_serializing_if = "Option::is_none")]
    pub year: Option<i32>,
    /// The media genre
    #[serde(rename = "genre", skip_serializing_if = "Option::is_none")]
    pub genre: Option<String>,
    /// The coverArt id.
    #[serde(rename = "coverArt", skip_serializing_if = "Option::is_none")]
    pub cover_art: Option<String>,
    /// A file size of the media.
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    /// The mimeType of the media.
    #[serde(rename = "contentType", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    /// The file suffix of the media.
    #[serde(rename = "suffix", skip_serializing_if = "Option::is_none")]
    pub suffix: Option<String>,
    /// The transcoded mediaType if transcoding should happen.
    #[serde(
        rename = "transcodedContentType",
        skip_serializing_if = "Option::is_none"
    )]
    pub transcoded_content_type: Option<String>,
    /// The file suffix of the transcoded media.
    #[serde(rename = "transcodedSuffix", skip_serializing_if = "Option::is_none")]
    pub transcoded_suffix: Option<String>,
    /// The duration of the media in seconds.
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<i32>,
    /// The bitrate of the media.
    #[serde(rename = "bitRate", skip_serializing_if = "Option::is_none")]
    pub bit_rate: Option<i32>,
    /// The bit depth of the media.
    #[serde(rename = "bitDepth", skip_serializing_if = "Option::is_none")]
    pub bit_depth: Option<i32>,
    /// The sampling rate of the media.
    #[serde(rename = "samplingRate", skip_serializing_if = "Option::is_none")]
    pub sampling_rate: Option<i32>,
    /// The number of channels of the media.
    #[serde(rename = "channelCount", skip_serializing_if = "Option::is_none")]
    pub channel_count: Option<i32>,
    /// The full path of the media.
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// Media is a video
    #[serde(rename = "isVideo", skip_serializing_if = "Option::is_none")]
    pub is_video: Option<bool>,
    /// The user rating of the media [1-5]
    #[serde(rename = "userRating", skip_serializing_if = "Option::is_none")]
    pub user_rating: Option<i32>,
    /// The average rating of the media [1.0-5.0]
    #[serde(rename = "averageRating", skip_serializing_if = "Option::is_none")]
    pub average_rating: Option<f64>,
    /// The play count.
    #[serde(rename = "playCount", skip_serializing_if = "Option::is_none")]
    pub play_count: Option<i32>,
    /// The disc number.
    #[serde(rename = "discNumber", skip_serializing_if = "Option::is_none")]
    pub disc_number: Option<i32>,
    /// Date the media was created. [ISO 8601]
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Date the media was starred. [ISO 8601]
    #[serde(rename = "starred", skip_serializing_if = "Option::is_none")]
    pub starred: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The corresponding album id
    #[serde(rename = "albumId", skip_serializing_if = "Option::is_none")]
    pub album_id: Option<String>,
    /// The corresponding artist id
    #[serde(rename = "artistId", skip_serializing_if = "Option::is_none")]
    pub artist_id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::GenericMediaType>,
    #[serde(rename = "mediaType", skip_serializing_if = "Option::is_none")]
    pub media_type: Option<models::MediaType>,
    /// The bookmark position in seconds
    #[serde(rename = "bookmarkPosition", skip_serializing_if = "Option::is_none")]
    pub bookmark_position: Option<i32>,
    /// The video original Width
    #[serde(rename = "originalWidth", skip_serializing_if = "Option::is_none")]
    pub original_width: Option<i32>,
    /// The video original Height
    #[serde(rename = "originalHeight", skip_serializing_if = "Option::is_none")]
    pub original_height: Option<i32>,
    /// Date the album was last played. [ISO 8601]
    #[serde(rename = "played", skip_serializing_if = "Option::is_none")]
    pub played: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The BPM of the song.
    #[serde(rename = "bpm", skip_serializing_if = "Option::is_none")]
    pub bpm: Option<i32>,
    /// The comment tag of the song.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// The song sort name.
    #[serde(rename = "sortName", skip_serializing_if = "Option::is_none")]
    pub sort_name: Option<String>,
    /// The track MusicBrainzID.
    #[serde(rename = "musicBrainzId", skip_serializing_if = "Option::is_none")]
    pub music_brainz_id: Option<String>,
    /// The track ISRC(s).
    #[serde(rename = "isrc", skip_serializing_if = "Option::is_none")]
    pub isrc: Option<Vec<String>>,
    /// The list of all genres of the song.
    #[serde(rename = "genres", skip_serializing_if = "Option::is_none")]
    pub genres: Option<Vec<models::ItemGenre>>,
    /// The list of all song artists of the song. (Note: Only the required `ArtistID3` fields should be returned by default)
    #[serde(rename = "artists", skip_serializing_if = "Option::is_none")]
    pub artists: Option<Vec<models::ArtistId3>>,
    /// The single value display artist.
    #[serde(rename = "displayArtist", skip_serializing_if = "Option::is_none")]
    pub display_artist: Option<String>,
    /// The list of all album artists of the song. (Note: Only the required `ArtistID3` fields should be returned by default)
    #[serde(rename = "albumArtists", skip_serializing_if = "Option::is_none")]
    pub album_artists: Option<Vec<models::ArtistId3>>,
    /// The single value display album artist.
    #[serde(rename = "displayAlbumArtist", skip_serializing_if = "Option::is_none")]
    pub display_album_artist: Option<String>,
    /// The list of all contributor artists of the song.
    #[serde(rename = "contributors", skip_serializing_if = "Option::is_none")]
    pub contributors: Option<Vec<models::Contributor>>,
    /// The single value display composer.
    #[serde(rename = "displayComposer", skip_serializing_if = "Option::is_none")]
    pub display_composer: Option<String>,
    /// The list of all moods of the song.
    #[serde(rename = "moods", skip_serializing_if = "Option::is_none")]
    pub moods: Option<Vec<String>>,
    /// The replay gain data of the song.
    #[serde(rename = "replayGain", skip_serializing_if = "Option::is_none")]
    pub replay_gain: Option<Box<models::ReplayGain>>,
    #[serde(rename = "explicitStatus", skip_serializing_if = "Option::is_none")]
    pub explicit_status: Option<models::ExplicitStatus>,
    /// The list of works associated with the song.
    #[serde(rename = "works", skip_serializing_if = "Option::is_none")]
    pub works: Option<Vec<models::Work>>,
    /// The list of movements associated with the song.
    #[serde(rename = "movements", skip_serializing_if = "Option::is_none")]
    pub movements: Option<Vec<models::Movement>>,
    /// The list of groupings associated with the song.
    #[serde(rename = "groupings", skip_serializing_if = "Option::is_none")]
    pub groupings: Option<Vec<String>>,
    /// The username
    #[serde(rename = "username")]
    pub username: String,
    /// Last update
    #[serde(rename = "minutesAgo")]
    pub minutes_ago: i32,
    /// Player Id
    #[serde(rename = "playerId")]
    pub player_id: i32,
    /// Player name
    #[serde(rename = "playerName", skip_serializing_if = "Option::is_none")]
    pub player_name: Option<String>,
    /// Playback state.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    /// Current playback position in milliseconds (Calculated by the server from the last playbackReport call received)
    #[serde(rename = "positionMs", skip_serializing_if = "Option::is_none")]
    pub position_ms: Option<i32>,
    /// Playback speed multiplier
    #[serde(rename = "playbackRate", skip_serializing_if = "Option::is_none")]
    pub playback_rate: Option<f32>,
}

impl NowPlayingEntry {
    pub fn new(
        id: String,
        is_dir: bool,
        title: String,
        username: String,
        minutes_ago: i32,
        player_id: i32,
    ) -> NowPlayingEntry {
        NowPlayingEntry {
            id,
            parent: None,
            is_dir,
            title,
            album: None,
            artist: None,
            track: None,
            year: None,
            genre: None,
            cover_art: None,
            size: None,
            content_type: None,
            suffix: None,
            transcoded_content_type: None,
            transcoded_suffix: None,
            duration: None,
            bit_rate: None,
            bit_depth: None,
            sampling_rate: None,
            channel_count: None,
            path: None,
            is_video: None,
            user_rating: None,
            average_rating: None,
            play_count: None,
            disc_number: None,
            created: None,
            starred: None,
            album_id: None,
            artist_id: None,
            r#type: None,
            media_type: None,
            bookmark_position: None,
            original_width: None,
            original_height: None,
            played: None,
            bpm: None,
            comment: None,
            sort_name: None,
            music_brainz_id: None,
            isrc: None,
            genres: None,
            artists: None,
            display_artist: None,
            album_artists: None,
            display_album_artist: None,
            contributors: None,
            display_composer: None,
            moods: None,
            replay_gain: None,
            explicit_status: None,
            works: None,
            movements: None,
            groupings: None,
            username,
            minutes_ago,
            player_id,
            player_name: None,
            state: None,
            position_ms: None,
            playback_rate: None,
        }
    }
}
/// Playback state.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "starting")]
    Starting,
    #[serde(rename = "playing")]
    Playing,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "stopped")]
    Stopped,
}

impl Default for State {
    fn default() -> State {
        Self::Starting
    }
}
