/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OpenSubsonicExtension : A supported OpenSubsonic API extension.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenSubsonicExtension {
    /// The name of the extension.
    #[serde(rename = "name")]
    pub name: String,
    /// The list of supported versions of the this extension.
    #[serde(rename = "versions")]
    pub versions: Vec<i32>,
}

impl OpenSubsonicExtension {
    /// A supported OpenSubsonic API extension.
    pub fn new(name: String, versions: Vec<i32>) -> OpenSubsonicExtension {
        OpenSubsonicExtension { name, versions }
    }
}
