/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Playlists : Playlists.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Playlists {
    /// The playlists
    #[serde(rename = "playlist", skip_serializing_if = "Option::is_none")]
    pub playlist: Option<Vec<models::Playlist>>,
}

impl Playlists {
    /// Playlists.
    pub fn new() -> Playlists {
        Playlists { playlist: None }
    }
}
