/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaylistWithSongs {
    /// Id of the playlist
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the playlist
    #[serde(rename = "name")]
    pub name: String,
    /// A comment
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// Owner of the playlist
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    /// Is the playlist public
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<bool>,
    /// number of songs
    #[serde(rename = "songCount")]
    pub song_count: i32,
    /// Playlist duration in seconds
    #[serde(rename = "duration")]
    pub duration: i32,
    /// Creation date [ISO 8601]
    #[serde(rename = "created")]
    pub created: chrono::DateTime<chrono::FixedOffset>,
    /// Last changed date [ISO 8601]
    #[serde(rename = "changed")]
    pub changed: chrono::DateTime<chrono::FixedOffset>,
    /// A cover Art Id
    #[serde(rename = "coverArt", skip_serializing_if = "Option::is_none")]
    pub cover_art: Option<String>,
    /// A list of allowed usernames
    #[serde(rename = "allowedUser", skip_serializing_if = "Option::is_none")]
    pub allowed_user: Option<Vec<String>>,
    /// [OS] If true the playlist cannot be edited by the current user
    #[serde(rename = "readonly", skip_serializing_if = "Option::is_none")]
    pub readonly: Option<bool>,
    /// [OS] Date the playlist contents are considered valid until [ISO 8601]. Empty or absent means no caching guarantee.
    #[serde(rename = "validUntil", skip_serializing_if = "Option::is_none")]
    pub valid_until: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The list of songs
    #[serde(rename = "entry", skip_serializing_if = "Option::is_none")]
    pub entry: Option<Vec<models::Child>>,
}

impl PlaylistWithSongs {
    pub fn new(
        id: String,
        name: String,
        song_count: i32,
        duration: i32,
        created: chrono::DateTime<chrono::FixedOffset>,
        changed: chrono::DateTime<chrono::FixedOffset>,
    ) -> PlaylistWithSongs {
        PlaylistWithSongs {
            id,
            name,
            comment: None,
            owner: None,
            public: None,
            song_count,
            duration,
            created,
            changed,
            cover_art: None,
            allowed_user: None,
            readonly: None,
            valid_until: None,
            entry: None,
        }
    }
}
