/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlayQueueByIndex : NowPlayingEntry with queue index.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlayQueueByIndex {
    /// Index of currently playing track.  This must be provided if one or more entries exists
    #[serde(rename = "currentIndex", skip_serializing_if = "Option::is_none")]
    pub current_index: Option<i32>,
    /// Position in milliseconds of currently playing track. If not provided, treat this value as 0
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
    /// The user this queue belongs to
    #[serde(rename = "username")]
    pub username: String,
    /// Date modified [ISO 8601]
    #[serde(rename = "changed")]
    pub changed: chrono::DateTime<chrono::FixedOffset>,
    /// Name of client app
    #[serde(rename = "changedBy")]
    pub changed_by: String,
    /// The list of songs in the queue
    #[serde(rename = "entry", skip_serializing_if = "Option::is_none")]
    pub entry: Option<Vec<models::Child>>,
}

impl PlayQueueByIndex {
    /// NowPlayingEntry with queue index.
    pub fn new(
        username: String,
        changed: chrono::DateTime<chrono::FixedOffset>,
        changed_by: String,
    ) -> PlayQueueByIndex {
        PlayQueueByIndex {
            current_index: None,
            position: None,
            username,
            changed,
            changed_by,
            entry: None,
        }
    }
}
