/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PodcastStatus : An enumeration of possible podcast statuses
/// An enumeration of possible podcast statuses
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PodcastStatus {
    #[serde(rename = "new")]
    New,
    #[serde(rename = "downloading")]
    Downloading,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "deleted")]
    Deleted,
    #[serde(rename = "skipped")]
    Skipped,
}

impl std::fmt::Display for PodcastStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::New => write!(f, "new"),
            Self::Downloading => write!(f, "downloading"),
            Self::Completed => write!(f, "completed"),
            Self::Error => write!(f, "error"),
            Self::Deleted => write!(f, "deleted"),
            Self::Skipped => write!(f, "skipped"),
        }
    }
}

impl Default for PodcastStatus {
    fn default() -> PodcastStatus {
        Self::New
    }
}
