/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Podcasts : Podcasts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Podcasts {
    /// Podcast channel(s)
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<Vec<models::PodcastChannel>>,
}

impl Podcasts {
    /// Podcasts.
    pub fn new() -> Podcasts {
        Podcasts { channel: None }
    }
}
