/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PodcastChannel : A Podcast channel
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PodcastChannel {
    /// The channel ID
    #[serde(rename = "id")]
    pub id: String,
    /// Podcast channel URL
    #[serde(rename = "url")]
    pub url: String,
    /// The channel title
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The channel description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// ID used for retrieving cover art
    #[serde(rename = "coverArt", skip_serializing_if = "Option::is_none")]
    pub cover_art: Option<String>,
    /// URL for original image of podcast channel
    #[serde(rename = "originalImageUrl", skip_serializing_if = "Option::is_none")]
    pub original_image_url: Option<String>,
    #[serde(rename = "status")]
    pub status: models::PodcastStatus,
    /// An error message
    #[serde(rename = "errorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    /// Podcast episodes with this channel
    #[serde(rename = "episode", skip_serializing_if = "Option::is_none")]
    pub episode: Option<Vec<models::PodcastEpisode>>,
}

impl PodcastChannel {
    /// A Podcast channel
    pub fn new(id: String, url: String, status: models::PodcastStatus) -> PodcastChannel {
        PodcastChannel {
            id,
            url,
            title: None,
            description: None,
            cover_art: None,
            original_image_url: None,
            status,
            error_message: None,
            episode: None,
        }
    }
}
