/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecordLabel : A record label for an album.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordLabel {
    #[serde(rename = "name")]
    pub name: String,
}

impl RecordLabel {
    /// A record label for an album.
    pub fn new(name: String) -> RecordLabel {
        RecordLabel { name }
    }
}
