/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReplayGain : The replay gain data of a song. Note: If the data is not present the field must be ommited in the answer. (But the replayGain field on Child must always be present)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplayGain {
    /// The track replay gain value. (In Db)
    #[serde(rename = "trackGain", skip_serializing_if = "Option::is_none")]
    pub track_gain: Option<f64>,
    /// The album replay gain value. (In Db)
    #[serde(rename = "albumGain", skip_serializing_if = "Option::is_none")]
    pub album_gain: Option<f64>,
    /// The track peak value. (Must be positive)
    #[serde(rename = "trackPeak", skip_serializing_if = "Option::is_none")]
    pub track_peak: Option<f64>,
    /// The album peak value. (Must be positive)
    #[serde(rename = "albumPeak", skip_serializing_if = "Option::is_none")]
    pub album_peak: Option<f64>,
    /// The base gain value. (In Db) (Ogg Opus Output Gain for example)
    #[serde(rename = "baseGain", skip_serializing_if = "Option::is_none")]
    pub base_gain: Option<f64>,
    /// An optional fallback gain that clients should apply when the corresponding gain value is missing. (Can be computed from the tracks or exposed as an user setting.)
    #[serde(rename = "fallbackGain", skip_serializing_if = "Option::is_none")]
    pub fallback_gain: Option<f64>,
}

impl ReplayGain {
    /// The replay gain data of a song. Note: If the data is not present the field must be ommited in the answer. (But the replayGain field on Child must always be present)
    pub fn new() -> ReplayGain {
        ReplayGain {
            track_gain: None,
            album_gain: None,
            track_peak: None,
            album_peak: None,
            base_gain: None,
            fallback_gain: None,
        }
    }
}
