/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScanStatus : Scan status information.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScanStatus {
    /// The status of the scan
    #[serde(rename = "scanning")]
    pub scanning: bool,
    /// Scanned item count
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}

impl ScanStatus {
    /// Scan status information.
    pub fn new(scanning: bool) -> ScanStatus {
        ScanStatus {
            scanning,
            count: None,
        }
    }
}
