/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Search3ResponseSubsonicResponse {
    Search3SuccessResponse(Box<models::Search3SuccessResponse>),
    SubsonicFailureResponse(Box<models::SubsonicFailureResponse>),
}

impl Default for Search3ResponseSubsonicResponse {
    fn default() -> Self {
        Self::Search3SuccessResponse(Default::default())
    }
}
/// The command result. `failed`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Failed
    }
}
