/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Search3Response : A subsonic-response element with a nested `searchResult3` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Search3Response {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::Search3ResponseSubsonicResponse>>,
}

impl Search3Response {
    /// A subsonic-response element with a nested `searchResult3` element on success.
    pub fn new() -> Search3Response {
        Search3Response {
            subsonic_response: None,
        }
    }
}
