/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchResult3 : searchResult3
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchResult3 {
    /// Matching artists
    #[serde(rename = "artist", skip_serializing_if = "Option::is_none")]
    pub artist: Option<Vec<models::ArtistId3>>,
    /// Matching albums
    #[serde(rename = "album", skip_serializing_if = "Option::is_none")]
    pub album: Option<Vec<models::AlbumId3>>,
    /// Matching songs
    #[serde(rename = "song", skip_serializing_if = "Option::is_none")]
    pub song: Option<Vec<models::Child>>,
}

impl SearchResult3 {
    /// searchResult3
    pub fn new() -> SearchResult3 {
        SearchResult3 {
            artist: None,
            album: None,
            song: None,
        }
    }
}
