/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Search3SuccessResponse {
    /// The server supported Subsonic API version.
    #[serde(rename = "version")]
    pub version: String,
    /// The server actual name. [Ex: Navidrome or gonic]
    #[serde(rename = "type")]
    pub r#type: String,
    /// The server version.
    #[serde(rename = "serverVersion")]
    pub server_version: String,
    /// Must return true if the server support OpenSubsonic API v1
    #[serde(rename = "openSubsonic")]
    pub open_subsonic: bool,
    /// The command result. `ok`
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "searchResult3")]
    pub search_result3: Box<models::SearchResult3>,
}

impl Search3SuccessResponse {
    pub fn new(
        version: String,
        r#type: String,
        server_version: String,
        open_subsonic: bool,
        status: Status,
        search_result3: models::SearchResult3,
    ) -> Search3SuccessResponse {
        Search3SuccessResponse {
            version,
            r#type,
            server_version,
            open_subsonic,
            status,
            search_result3: Box::new(search_result3),
        }
    }
}
/// The command result. `ok`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ok")]
    Ok,
}

impl Default for Status {
    fn default() -> Status {
        Self::Ok
    }
}
