/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchResponse : A subsonic-response element with a nested `searchResult` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::SearchResponseSubsonicResponse>>,
}

impl SearchResponse {
    /// A subsonic-response element with a nested `searchResult` element on success.
    pub fn new() -> SearchResponse {
        SearchResponse {
            subsonic_response: None,
        }
    }
}
