/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Shares : Shares.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Shares {
    /// A list of share
    #[serde(rename = "share", skip_serializing_if = "Option::is_none")]
    pub share: Option<Vec<models::Share>>,
}

impl Shares {
    /// Shares.
    pub fn new() -> Shares {
        Shares { share: None }
    }
}
