/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Share : Share.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Share {
    /// The share Id
    #[serde(rename = "id")]
    pub id: String,
    /// The share url
    #[serde(rename = "url")]
    pub url: String,
    /// A description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The username
    #[serde(rename = "username")]
    pub username: String,
    /// Creation date [ISO 8601]
    #[serde(rename = "created")]
    pub created: chrono::DateTime<chrono::FixedOffset>,
    /// Share expiration [ISO 8601]
    #[serde(rename = "expires", skip_serializing_if = "Option::is_none")]
    pub expires: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Last visit [ISO 8601]
    #[serde(rename = "lastVisited", skip_serializing_if = "Option::is_none")]
    pub last_visited: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Visit count
    #[serde(rename = "visitCount")]
    pub visit_count: i32,
    /// A list of share
    #[serde(rename = "entry", skip_serializing_if = "Option::is_none")]
    pub entry: Option<Vec<models::Child>>,
}

impl Share {
    /// Share.
    pub fn new(
        id: String,
        url: String,
        username: String,
        created: chrono::DateTime<chrono::FixedOffset>,
        visit_count: i32,
    ) -> Share {
        Share {
            id,
            url,
            description: None,
            username,
            created,
            expires: None,
            last_visited: None,
            visit_count,
            entry: None,
        }
    }
}
