/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SimilarSongs : SimilarSongs list.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimilarSongs {
    /// List of songs
    #[serde(rename = "song", skip_serializing_if = "Option::is_none")]
    pub song: Option<Vec<models::Child>>,
}

impl SimilarSongs {
    /// SimilarSongs list.
    pub fn new() -> SimilarSongs {
        SimilarSongs { song: None }
    }
}
