/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SonicMatch : A sonic match entry, containing a Child entry object and a normalized similarity score.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SonicMatch {
    #[serde(rename = "entry")]
    pub entry: Box<models::Child>,
    /// The normalized similarity score (1.0 = same exact song, 0.0 = most different). For getSonicSimilarTracks, relative to the query song. For findSonicPath, relative to the starting song. Returns -1 when similarity is not supported by the server.
    #[serde(rename = "similarity")]
    pub similarity: f64,
}

impl SonicMatch {
    /// A sonic match entry, containing a Child entry object and a normalized similarity score.
    pub fn new(entry: models::Child, similarity: f64) -> SonicMatch {
        SonicMatch {
            entry: Box::new(entry),
            similarity,
        }
    }
}
