/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StartScanResponse : A subsonic-response element with a nested `scanStatus` element on success.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StartScanResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::StartScanResponseSubsonicResponse>>,
}

impl StartScanResponse {
    /// A subsonic-response element with a nested `scanStatus` element on success.
    pub fn new() -> StartScanResponse {
        StartScanResponse {
            subsonic_response: None,
        }
    }
}
