/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Starred : starred.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Starred {
    /// Starred artists
    #[serde(rename = "artist", skip_serializing_if = "Option::is_none")]
    pub artist: Option<Vec<models::Artist>>,
    /// Starred albums
    #[serde(rename = "album", skip_serializing_if = "Option::is_none")]
    pub album: Option<Vec<models::Child>>,
    /// Starred songs
    #[serde(rename = "song", skip_serializing_if = "Option::is_none")]
    pub song: Option<Vec<models::Child>>,
}

impl Starred {
    /// starred.
    pub fn new() -> Starred {
        Starred {
            artist: None,
            album: None,
            song: None,
        }
    }
}
