/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StreamDetails {
    #[serde(rename = "protocol")]
    pub protocol: Protocol,
    #[serde(rename = "container")]
    pub container: String,
    #[serde(rename = "codec")]
    pub codec: String,
    #[serde(rename = "audioChannels", skip_serializing_if = "Option::is_none")]
    pub audio_channels: Option<i32>,
    #[serde(rename = "audioBitrate", skip_serializing_if = "Option::is_none")]
    pub audio_bitrate: Option<i32>,
    #[serde(rename = "audioProfile", skip_serializing_if = "Option::is_none")]
    pub audio_profile: Option<String>,
    #[serde(rename = "audioSamplerate", skip_serializing_if = "Option::is_none")]
    pub audio_samplerate: Option<i32>,
    #[serde(rename = "audioBitdepth", skip_serializing_if = "Option::is_none")]
    pub audio_bitdepth: Option<i32>,
}

impl StreamDetails {
    pub fn new(protocol: Protocol, container: String, codec: String) -> StreamDetails {
        StreamDetails {
            protocol,
            container,
            codec,
            audio_channels: None,
            audio_bitrate: None,
            audio_profile: None,
            audio_samplerate: None,
            audio_bitdepth: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Protocol {
    #[serde(rename = "http")]
    Http,
    #[serde(rename = "hls")]
    Hls,
}

impl Default for Protocol {
    fn default() -> Protocol {
        Self::Http
    }
}
