/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StructuredLyrics : Structured lyrics
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StructuredLyrics {
    /// The lyrics language (ideally ISO 639). If the language is unknown (e.g. lrc file), the server must return `und` (ISO standard) or `xxx` (common value for taggers). Ideally, the server will return lang as an ISO 639 (2/3) code. However, tagged files and external lyrics can come with any value as a potential language code, so clients should take care when displaying lang.  Furthermore, there is special behavior for the value xxx. While not an ISO code, it is commonly used by taggers and other parsing software. Clients should treat xxx as not having a specified language (equivalent to the und code).
    #[serde(rename = "lang")]
    pub lang: String,
    /// True if the lyrics are synced, false otherwise
    #[serde(rename = "synced")]
    pub synced: bool,
    /// The actual lyrics. Ordered by start time (synced) or appearance order (unsynced)
    #[serde(rename = "line")]
    pub line: Vec<models::Line>,
    /// The artist name to display. This could be the localized name, or any other value
    #[serde(rename = "displayArtist", skip_serializing_if = "Option::is_none")]
    pub display_artist: Option<String>,
    /// The title to display. This could be the song title (localized), or any other value
    #[serde(rename = "displayTitle", skip_serializing_if = "Option::is_none")]
    pub display_title: Option<String>,
    /// The offset to apply to all lyrics, in milliseconds. Positive means lyrics appear sooner, negative means later. If not included, the offset must be assumed to be 0
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<f64>,
    /// The primary lyric-layer classification for this structuredLyrics entry. One of: main (primary vocals for this entry, default if omitted), translation (a translation of another lyric layer into another language), pronunciation (a phonetic/romanized rendering, e.g. romaji for Japanese, pinyin for Chinese). Tracks are independent across kind values; clients should not assume 1:1 line or cue alignment between entries. Only returned when enhanced=true
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<Kind>,
    /// Reusable per-track attribution metadata for cueLine entries. When present, agents must contain at least one entry, and each agents[].id must be unique within this structuredLyrics entry. Agents are optional for simple unattributed single-layer lyrics. When a structuredLyrics entry represents multiple vocal agents or layers, it must include agents; a single-agent attributed or default entry may also include agents, and if it does, exactly one agent must use role main. Agents should not be emitted without cueLine data
    #[serde(rename = "agents", skip_serializing_if = "Option::is_none")]
    pub agents: Option<Vec<models::Agent>>,
    /// Word/syllable-level timing data. Each cueLine corresponds to a line in this structuredLyrics entry by its index field. Every cueLine includes value, and every cue includes byteStart and byteEnd offsets into that exact string. When agents split one parent line into multiple cueLines, each cueLine.value is the renderable text for that agent/layer, not necessarily the parent line's combined text. If agents is present, every cueLine in the entry must include agentId, and each agentId must match exactly one agents[].id in that entry. If agents is absent, cueLines must not include agentId. Only returned when enhanced=true and synced is true
    #[serde(rename = "cueLine", skip_serializing_if = "Option::is_none")]
    pub cue_line: Option<Vec<models::CueLine>>,
}

impl StructuredLyrics {
    /// Structured lyrics
    pub fn new(lang: String, synced: bool, line: Vec<models::Line>) -> StructuredLyrics {
        StructuredLyrics {
            lang,
            synced,
            line,
            display_artist: None,
            display_title: None,
            offset: None,
            kind: None,
            agents: None,
            cue_line: None,
        }
    }
}
/// The primary lyric-layer classification for this structuredLyrics entry. One of: main (primary vocals for this entry, default if omitted), translation (a translation of another lyric layer into another language), pronunciation (a phonetic/romanized rendering, e.g. romaji for Japanese, pinyin for Chinese). Tracks are independent across kind values; clients should not assume 1:1 line or cue alignment between entries. Only returned when enhanced=true
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "main")]
    Main,
    #[serde(rename = "translation")]
    Translation,
    #[serde(rename = "pronunciation")]
    Pronunciation,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Main
    }
}
