/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubsonicResponse : Common answer wrapper.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubsonicResponse {
    #[serde(rename = "subsonic-response", skip_serializing_if = "Option::is_none")]
    pub subsonic_response: Option<Box<models::SubsonicResponseSubsonicResponse>>,
}

impl SubsonicResponse {
    /// Common answer wrapper.
    pub fn new() -> SubsonicResponse {
        SubsonicResponse {
            subsonic_response: None,
        }
    }
}
