/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Deserialize_repr, Serialize_repr};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubsonicError {
    /// The error code. * 0: A generic error. * 10: Required parameter is missing. * 20: Incompatible Subsonic REST protocol version. Client must upgrade. * 30: Incompatible Subsonic REST protocol version. Server must upgrade. * 40: Wrong username or password. * 41: Token authentication not supported for LDAP users. * 42: Provided authentication mechanism not supported. * 43: Multiple conflicting authentication mechanisms provided. * 44: Invalid API key. * 50: User is not authorized for the given operation. * 60: The trial period for the Subsonic server is over. Please upgrade to Subsonic Premium. Visit subsonic.org for details. * 70: The requested data was not found.
    #[serde(rename = "code")]
    pub code: Code,
    /// The optional error message
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// A URL (documentation, configuration, etc) which may provide additional context for the error)
    #[serde(rename = "helpUrl", skip_serializing_if = "Option::is_none")]
    pub help_url: Option<String>,
}

impl SubsonicError {
    pub fn new(code: Code) -> SubsonicError {
        SubsonicError {
            code,
            message: None,
            help_url: None,
        }
    }
}
/// The error code. * 0: A generic error. * 10: Required parameter is missing. * 20: Incompatible Subsonic REST protocol version. Client must upgrade. * 30: Incompatible Subsonic REST protocol version. Server must upgrade. * 40: Wrong username or password. * 41: Token authentication not supported for LDAP users. * 42: Provided authentication mechanism not supported. * 43: Multiple conflicting authentication mechanisms provided. * 44: Invalid API key. * 50: User is not authorized for the given operation. * 60: The trial period for the Subsonic server is over. Please upgrade to Subsonic Premium. Visit subsonic.org for details. * 70: The requested data was not found.
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum Code {
    Variant0 = 0,
    Variant10 = 10,
    Variant20 = 20,
    Variant30 = 30,
    Variant40 = 40,
    Variant41 = 41,
    Variant42 = 42,
    Variant43 = 43,
    Variant44 = 44,
    Variant50 = 50,
    Variant60 = 60,
    Variant70 = 70,
}

impl std::fmt::Display for Code {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::Variant0 => "0",
                Self::Variant10 => "10",
                Self::Variant20 => "20",
                Self::Variant30 => "30",
                Self::Variant40 => "40",
                Self::Variant41 => "41",
                Self::Variant42 => "42",
                Self::Variant43 => "43",
                Self::Variant44 => "44",
                Self::Variant50 => "50",
                Self::Variant60 => "60",
                Self::Variant70 => "70",
            }
        )
    }
}

impl Default for Code {
    fn default() -> Code {
        Self::Variant0
    }
}
