/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubsonicBaseResponse {
    /// The server supported Subsonic API version.
    #[serde(rename = "version")]
    pub version: String,
    /// The server actual name. [Ex: Navidrome or gonic]
    #[serde(rename = "type")]
    pub r#type: String,
    /// The server version.
    #[serde(rename = "serverVersion")]
    pub server_version: String,
    /// Must return true if the server support OpenSubsonic API v1
    #[serde(rename = "openSubsonic")]
    pub open_subsonic: bool,
}

impl SubsonicBaseResponse {
    pub fn new(
        version: String,
        r#type: String,
        server_version: String,
        open_subsonic: bool,
    ) -> SubsonicBaseResponse {
        SubsonicBaseResponse {
            version,
            r#type,
            server_version,
            open_subsonic,
        }
    }
}
