/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TokenInfo : Information about an API key
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenInfo {
    /// Username associated with token
    #[serde(rename = "username")]
    pub username: String,
}

impl TokenInfo {
    /// Information about an API key
    pub fn new(username: String) -> TokenInfo {
        TokenInfo { username }
    }
}
