/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TopSongs : TopSongs list.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopSongs {
    /// List of songs
    #[serde(rename = "song", skip_serializing_if = "Option::is_none")]
    pub song: Option<Vec<models::Child>>,
}

impl TopSongs {
    /// TopSongs list.
    pub fn new() -> TopSongs {
        TopSongs { song: None }
    }
}
