/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TranscodeDecision {
    #[serde(rename = "canDirectPlay")]
    pub can_direct_play: bool,
    #[serde(rename = "canTranscode")]
    pub can_transcode: bool,
    #[serde(rename = "transcodeReason", skip_serializing_if = "Option::is_none")]
    pub transcode_reason: Option<Vec<String>>,
    #[serde(rename = "errorReason", skip_serializing_if = "Option::is_none")]
    pub error_reason: Option<String>,
    #[serde(rename = "transcodeParams", skip_serializing_if = "Option::is_none")]
    pub transcode_params: Option<String>,
    #[serde(rename = "sourceStream", skip_serializing_if = "Option::is_none")]
    pub source_stream: Option<Box<models::StreamDetails>>,
    #[serde(rename = "transcodeStream", skip_serializing_if = "Option::is_none")]
    pub transcode_stream: Option<Box<models::StreamDetails>>,
}

impl TranscodeDecision {
    pub fn new(can_direct_play: bool, can_transcode: bool) -> TranscodeDecision {
        TranscodeDecision {
            can_direct_play,
            can_transcode,
            transcode_reason: None,
            error_reason: None,
            transcode_params: None,
            source_stream: None,
            transcode_stream: None,
        }
    }
}
