/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Transcoding : The transcoding extension
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transcoding {
    /// The name of the extension.
    #[serde(rename = "name")]
    pub name: Name,
    /// The version of the extension.
    #[serde(rename = "version")]
    pub version: String,
    /// The endpoints provided by this extension.
    #[serde(rename = "endpoints")]
    pub endpoints: Vec<String>,
}

impl Transcoding {
    /// The transcoding extension
    pub fn new(name: Name, version: String, endpoints: Vec<String>) -> Transcoding {
        Transcoding {
            name,
            version,
            endpoints,
        }
    }
}
/// The name of the extension.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "transcoding")]
    Transcoding,
}

impl Default for Name {
    fn default() -> Name {
        Self::Transcoding
    }
}
