/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TranscodingProfile {
    #[serde(rename = "container")]
    pub container: String,
    #[serde(rename = "audioCodec")]
    pub audio_codec: String,
    #[serde(rename = "protocol")]
    pub protocol: Protocol,
    #[serde(rename = "maxAudioChannels", skip_serializing_if = "Option::is_none")]
    pub max_audio_channels: Option<i32>,
}

impl TranscodingProfile {
    pub fn new(container: String, audio_codec: String, protocol: Protocol) -> TranscodingProfile {
        TranscodingProfile {
            container,
            audio_codec,
            protocol,
            max_audio_channels: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Protocol {
    #[serde(rename = "http")]
    Http,
    #[serde(rename = "hls")]
    Hls,
}

impl Default for Protocol {
    fn default() -> Protocol {
        Self::Http
    }
}
