/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Users : users.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Users {
    /// Array of users
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Vec<models::User>>,
}

impl Users {
    /// users.
    pub fn new() -> Users {
        Users { user: None }
    }
}
