/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// User : user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    /// Username
    #[serde(rename = "username")]
    pub username: String,
    /// Scrobbling enabled
    #[serde(rename = "scrobblingEnabled")]
    pub scrobbling_enabled: bool,
    #[serde(rename = "maxBitRate", skip_serializing_if = "Option::is_none")]
    pub max_bit_rate: Option<i32>,
    /// Whether the user is an admin
    #[serde(rename = "adminRole")]
    pub admin_role: bool,
    /// Whether the user is can edit settings
    #[serde(rename = "settingsRole")]
    pub settings_role: bool,
    /// Whether the user can download
    #[serde(rename = "downloadRole")]
    pub download_role: bool,
    /// Whether the user can upload
    #[serde(rename = "uploadRole")]
    pub upload_role: bool,
    /// Whether the user can create playlists
    #[serde(rename = "playlistRole")]
    pub playlist_role: bool,
    /// Whether the user can get cover art
    #[serde(rename = "coverArtRole")]
    pub cover_art_role: bool,
    /// Whether the user can create comments
    #[serde(rename = "commentRole")]
    pub comment_role: bool,
    /// Whether the user can create/refresh podcasts
    #[serde(rename = "podcastRole")]
    pub podcast_role: bool,
    /// Whether the user can stream
    #[serde(rename = "streamRole")]
    pub stream_role: bool,
    /// Whether the user can control the jukebox
    #[serde(rename = "jukeboxRole")]
    pub jukebox_role: bool,
    /// Whether the user can create a stream
    #[serde(rename = "shareRole")]
    pub share_role: bool,
    /// Whether the user can convert videos
    #[serde(rename = "videoConversionRole")]
    pub video_conversion_role: bool,
    /// Last time the avatar was changed [ISO 8601]
    #[serde(rename = "avatarLastChanged", skip_serializing_if = "Option::is_none")]
    pub avatar_last_changed: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Folder ID(s)
    #[serde(rename = "folder", skip_serializing_if = "Option::is_none")]
    pub folder: Option<Vec<i32>>,
}

impl User {
    /// user.
    pub fn new(
        username: String,
        scrobbling_enabled: bool,
        admin_role: bool,
        settings_role: bool,
        download_role: bool,
        upload_role: bool,
        playlist_role: bool,
        cover_art_role: bool,
        comment_role: bool,
        podcast_role: bool,
        stream_role: bool,
        jukebox_role: bool,
        share_role: bool,
        video_conversion_role: bool,
    ) -> User {
        User {
            username,
            scrobbling_enabled,
            max_bit_rate: None,
            admin_role,
            settings_role,
            download_role,
            upload_role,
            playlist_role,
            cover_art_role,
            comment_role,
            podcast_role,
            stream_role,
            jukebox_role,
            share_role,
            video_conversion_role,
            avatar_last_changed: None,
            folder: None,
        }
    }
}
