/*
 * OpenSubsonic API
 *
 * OpenSubsonic API documentation.
 *
 * The version of the OpenAPI document: 1.16.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Work : A work associated with a song.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Work {
    /// The work name.
    #[serde(rename = "name")]
    pub name: String,
    /// The MusicBrainz Work ID.
    #[serde(rename = "musicBrainzId", skip_serializing_if = "Option::is_none")]
    pub music_brainz_id: Option<String>,
}

impl Work {
    /// A work associated with a song.
    pub fn new(name: String) -> Work {
        Work {
            name,
            music_brainz_id: None,
        }
    }
}
